### ISSUE TITLE
Detect invalid trees

### ISSUE THREAD

**Issue by ketch** [SciML/RootedTrees.jl#102]
Currently
```
RootedTree([1,1])
```
results in a valid rooted tree.  If one uses the `butcher` printing style, the result is actually shown as the [1,2] tree.

<img width="510" alt="Screen Shot 2023-02-20 at 4 34 02 AM" src="https://user-images.githubusercontent.com/697763/219958111-ddea6185-34fa-482c-afeb-6e7f499e02ae.png">

We get the same thing from
```
RootedTree([1,3])
```
and
```
RootedTree([1,0])
```

**Comment by ketch** [comment]
So far, all the invalid trees I can construct would be caught if we checked that every subsequent entry of the level sequence has value greater than the root.

**Comment by ranocha** [comment]
I would like to discourage calling `RootedTree` since I would like to keep it as some form of low-overhead but unsafe constructor. But we should add some checks to the recommended version `rootedtree`.
