### ISSUE TITLE
Hook into Latexify

### ISSUE THREAD

**Issue by ranocha** [SciML/RootedTrees.jl#29]
It could be an option to allow pretty printing of rooted tree in LaTeX via something like
```
% Butcher trees, cf. https://tex.stackexchange.com/questions/283343/butcher-trees-in-tikz
\usepackage{forest}
\forestset{
  */.style={
    delay+={append={[]},}
  },
  rooted tree/.style={
    for tree={
      grow'=90,
      parent anchor=center,
      child anchor=center,
      s sep=2.5pt,
      if level=0{
        baseline
      }{},
      delay={
        if content={*}{
          content=,
          append={[]}
        }{}
      }
    },
    before typesetting nodes={
      for tree={
        circle,
        fill,
        minimum width=3pt,
        inner sep=0pt,
        child anchor=center,
      },
    },
    before computing xy={
      for tree={
        l=5pt,
      }
    }
  }
}
\DeclareDocumentCommand\rootedtree{o}{\Forest{rooted tree [#1]}}
```
and `\rootedtree[[],[]], \rootedtree[[[]]]` etc.

**Comment by ranocha** [comment]
@ketch Or would you suggest another LaTeX package or another approach for this?

**Comment by ketch** [comment]
I'm not sure what you mean; the snippet above is latex code, right?  What is the connection to Julia?

**Comment by ranocha** [comment]
There is a Julia package [Latexify.jl](https://github.com/korsbo/Latexify.jl) that provides the function `latexify` which can be used to generate LaTeX expressions from Julia objects. The idea would be to overload this function to hook into the LaTeX printing system of Julia. Then, the question would be what kind of LaTeX package to use for displaying rooted trees.

**Comment by ranocha** [comment]
On the other hand, it is probably not that nice to rely on LaTeX packages, but I don't know any other self=contained and readable way to present rooted trees in LaTeX.

**Comment by ketch** [comment]
Okay, I think the package you have suggested is what I would prefer.  There is also planar forest, but it requires running pythontex, which is a bit more hassle.

By the way, the string of brackets required here is exactly what you get if you convert the nested list representation (in my Python code) to a string.
